#!/bin/bash
echo "Enter the directory name"
read folder
echo "creating folder..."
mkdir "$folder"
echo "entering folder..."
cd $folder
echo "enter readme"
read readme
echo "$readme" >> README.md
echo "created readme"
echo "folder created and initialized"
#cd $folder
