#!/bin/bash
echo "Enter the folder name"
read folder
echo "creatind folder..."
mkdir $folder
echo "entering folder..."
cd $folder
echo "enter readme"
read readme
echo "$readme" >> README.md
echo "created readme"
echo "folder created and initialized"
cd $folder
